name: Update App Config
on:
  push:
    paths:
      - 'editor.json'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Config
        run: |
          echo "No complex sed needed for now"
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Manual update config" || echo "Nothing to commit"
          git push
